-- AKADEMO · Contatos
-- Execute este arquivo depois de schema.sql e teachers-migration.sql.
-- Professores continuam na tabela public.professores para manter os vínculos
-- com disciplinas. Os outros tipos ficam em public.contatos.

create extension if not exists pgcrypto;

create table if not exists public.contatos (
  id bigint generated by default as identity primary key,
  email_user text not null,
  perfil uuid not null references public.perfil_estudo(id) on delete cascade,
  nome text not null check (char_length(btrim(nome)) between 1 and 120),
  tipo integer not null check (tipo between 0 and 5),
  telefone bigint,
  email text,
  obs text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contatos_telefone_check check (telefone is null or telefone > 0)
);

-- Compatibilidade com uma tabela criada manualmente antes desta migração.
alter table public.contatos add column if not exists email_user text;
alter table public.contatos add column if not exists perfil uuid;
alter table public.contatos add column if not exists nome text;
alter table public.contatos add column if not exists tipo integer;
alter table public.contatos add column if not exists telefone bigint;
alter table public.contatos add column if not exists email text;
alter table public.contatos add column if not exists obs text;
alter table public.contatos add column if not exists created_at timestamptz default now();
alter table public.contatos add column if not exists updated_at timestamptz default now();

-- O telefone do contato é um bigint com DDI + número, sem o sinal de +.
-- A conversão abaixo também corrige colunas antigas que tenham sido criadas como texto.
do $$
declare phone_type regtype;
begin
  select atttypid::regtype into phone_type
  from pg_attribute
  where attrelid = 'public.contatos'::regclass
    and attname = 'telefone'
    and not attisdropped;

  if phone_type is distinct from 'bigint'::regtype then
    execute $sql$
      alter table public.contatos
      alter column telefone type bigint
      using nullif(regexp_replace(telefone::text, '[^0-9]', '', 'g'), '')::bigint
    $sql$;
  end if;
end;
$$;

update public.contatos
set tipo = 5
where tipo is null or tipo not between 0 and 5;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.contatos'::regclass
      and conname = 'contatos_tipo_check'
  ) then
    alter table public.contatos add constraint contatos_tipo_check check (tipo between 0 and 5);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.contatos'::regclass
      and conname = 'contatos_telefone_check'
  ) then
    alter table public.contatos add constraint contatos_telefone_check check (telefone is null or telefone > 0);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.contatos'::regclass
      and conname = 'contatos_perfil_fkey'
  ) then
    alter table public.contatos add constraint contatos_perfil_fkey
      foreign key (perfil) references public.perfil_estudo(id) on delete cascade;
  end if;
end;
$$;

create index if not exists contatos_perfil_created_idx
  on public.contatos(perfil, created_at);
create index if not exists contatos_busca_idx
  on public.contatos(perfil, nome, tipo);

-- Observações passam a fazer parte do cadastro de professores, sem mudar seus IDs
-- ou qualquer vínculo já existente com disciplinas.
alter table public.professores add column if not exists obs text;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists contatos_set_updated_at on public.contatos;
create trigger contatos_set_updated_at
before update on public.contatos
for each row execute procedure public.set_updated_at();

-- Mantém os contatos alinhados caso o usuário altere o e-mail de autenticação.
create or replace function public.sync_auth_user_email()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_table text;
begin
  if new.email is distinct from old.email then
    update public.users
    set email = new.email, updated_at = now()
    where id = new.id;

    update public.perfil_estudo
    set email = new.email, updated_at = now()
    where user_id = new.id;

    -- Atualiza com segurança todas as tabelas do AKADEMO que usam
    -- email_user + perfil, inclusive professores e contatos, sem deixar
    -- de sincronizar módulos criados por migrações anteriores.
    for target_table in
      select relation.relname
      from pg_class as relation
      join pg_namespace as namespace on namespace.oid = relation.relnamespace
      where namespace.nspname = 'public'
        and relation.relkind = 'r'
        and exists (
          select 1 from pg_attribute
          where attrelid = relation.oid and attname = 'email_user' and not attisdropped
        )
        and exists (
          select 1 from pg_attribute
          where attrelid = relation.oid and attname = 'perfil' and not attisdropped
        )
        and exists (
          select 1 from pg_attribute
          where attrelid = relation.oid and attname = 'updated_at' and not attisdropped
        )
    loop
      execute format(
        'update public.%I as item set email_user = $1, updated_at = now() from public.perfil_estudo as profile where item.perfil = profile.id and profile.user_id = $2',
        target_table
      ) using new.email, new.id;
    end loop;
  end if;
  return new;
end;
$$;

alter table public.contatos enable row level security;
revoke all on table public.contatos from anon, authenticated;
grant select, insert, update, delete on table public.contatos to authenticated;

-- Colunas identity exigem permissÃ£o de uso na sequÃªncia para inserts feitos
-- pelo cliente autenticado. A consulta tambÃ©m funciona em instalaÃ§Ãµes legadas.
do $$
declare contact_sequence regclass;
begin
  select pg_get_serial_sequence('public.contatos', 'id')::regclass into contact_sequence;
  if contact_sequence is not null then
    execute format('grant usage, select on sequence %s to authenticated', contact_sequence);
  end if;
end;
$$;

drop policy if exists "contacts read own profile" on public.contatos;
create policy "contacts read own profile" on public.contatos
for select to authenticated using (
  email_user = (select auth.jwt() ->> 'email')
  and exists (
    select 1 from public.perfil_estudo as profile
    where profile.id = contatos.perfil and profile.user_id = (select auth.uid())
  )
);

drop policy if exists "contacts create own profile" on public.contatos;
create policy "contacts create own profile" on public.contatos
for insert to authenticated with check (
  email_user = (select auth.jwt() ->> 'email')
  and exists (
    select 1 from public.perfil_estudo as profile
    where profile.id = contatos.perfil and profile.user_id = (select auth.uid())
  )
);

drop policy if exists "contacts update own profile" on public.contatos;
create policy "contacts update own profile" on public.contatos
for update to authenticated
using (
  email_user = (select auth.jwt() ->> 'email')
  and exists (
    select 1 from public.perfil_estudo as profile
    where profile.id = contatos.perfil and profile.user_id = (select auth.uid())
  )
)
with check (
  email_user = (select auth.jwt() ->> 'email')
  and exists (
    select 1 from public.perfil_estudo as profile
    where profile.id = contatos.perfil and profile.user_id = (select auth.uid())
  )
);

drop policy if exists "contacts delete own profile" on public.contatos;
create policy "contacts delete own profile" on public.contatos
for delete to authenticated using (
  email_user = (select auth.jwt() ->> 'email')
  and exists (
    select 1 from public.perfil_estudo as profile
    where profile.id = contatos.perfil and profile.user_id = (select auth.uid())
  )
);

-- Mapeamento do campo tipo em public.contatos:
-- 0 Diretor | 1 Coordenador | 2 Mentor | 3 Funcionário | 4 Aluno | 5 Outro
-- Professor não é inserido nesta tabela: permanece em public.professores.
